
###############################################################################
#
# Inclusive Makefile for the BMI_utest module.
#
# Autogenerated 2015-03-04 19:09:27.585072
#
###############################################################################
BMI_utest_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

