# SPDX-FileCopyrightText: 2022 The P4 Language Consortium
#
# SPDX-License-Identifier: Apache-2.0

# XFAILS: tests that currently fail. Most of these are temporary.
# ================================================

# The code generated by the compiler is invalid.
p4tools_add_xfail_reason(
  "testgen-p4c-ebpf"
  "Failed to build the filter"
  ternary_ebpf.p4
  lpm_ebpf.p4
)

p4tools_add_xfail_reason(
  "testgen-p4c-ebpf"
  "fields wider than 64 bits are not supported yet"
  op_bin.p4
)

p4tools_add_xfail_reason(
  "testgen-p4c-ebpf"
  "Expected packets on port(s) .* not received"
)

p4tools_add_xfail_reason(
  "testgen-p4c-ebpf"
  "Expected .* packets on port .* got .*"
  issue2793_ebpf.p4
)

p4tools_add_xfail_reason(
  "testgen-p4c-ebpf"
  "IndexError: list index out of range"
)
