/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef runtime_TYPES_H
#define runtime_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace bm_runtime {

typedef int32_t BmEntryHandle;

typedef std::vector<std::string>  BmActionData;

typedef struct _InvalidTableOperation__isset {
  _InvalidTableOperation__isset() : what(false) {}
  bool what;
} _InvalidTableOperation__isset;

class InvalidTableOperation : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

  InvalidTableOperation() : what(0) {
  }

  virtual ~InvalidTableOperation() throw() {}

  int32_t what;

  _InvalidTableOperation__isset __isset;

  void __set_what(const int32_t val) {
    what = val;
  }

  bool operator == (const InvalidTableOperation & rhs) const
  {
    if (!(what == rhs.what))
      return false;
    return true;
  }
  bool operator != (const InvalidTableOperation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InvalidTableOperation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(InvalidTableOperation &a, InvalidTableOperation &b);

} // namespace

#endif
