###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := behavioral_utils
AUTOMODULE := behavioral_utils
include $(BUILDER)/definemodule.mk
