#################################################################
# 
#################################################################
include ../../init.mk

MODULE :=  testmod
AUTOMODULE :=  testmod

include $(BUILDER)/definemodule.mk
