
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2015-01-26 13:52:30.468099
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
behavioral_sim_BASEDIR := $(BASEDIR)behavioral_sim


ALL_MODULES := $(ALL_MODULES) behavioral_sim
