
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-10-08 14:44:18.996872
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
testmod_BASEDIR := $(BASEDIR)testmod

ALL_MODULES := $(ALL_MODULES) testmod

