#!/usr/bin/env bash
#
# Debian/Ubuntu Packaging Scripts
# Copyright (C) 2002-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# ====== Obtain package information =========================================
CHANGELOG_HEADER="`head -n1 debian/changelog`"
PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`


# ====== Clean up ===========================================================
rm -f *.deb *.dsc *.asc *.changes *.build *.upload *.tar.gz stamp-h* svn-commit* *~

for type in gz bz2 xz ; do
   find . -maxdepth 1 -name "${PACKAGE}-*.${type}" | xargs -r rm
   find . -maxdepth 1 -name "${PACKAGE}_*.${type}" | xargs -r rm
done
find . -maxdepth 1 -name "*.buildinfo" | xargs -r rm

shopt -s extglob
rm -rf ${PACKAGE}-+([0-9]).+([0-9]).+([0-9])*
