#!/usr/bin/perl
#
# Debian/Ubuntu Packaging Scripts
# Copyright (C) 2002-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

use warnings;
use strict;

my $mode=0;
my $entryLines=0;
my $entry="";

while (my $text = <STDIN>) {
   chomp $text;

   if($entryLines == 0) {
      if($text =~ /^[a-zA-Z].*$/) {
         $entry      = "$text\n\n";
         $entryLines = 1;
      }
   }
   else {
      if($text =~ /^[ \t]*$/) {
         # Remove empty line.
      }
      elsif($text =~ /^ --.*$/) {
         $entry  = "$entry\n$text\n";
         if($entryLines > 1) {
            print "$entry\n";
         }

         if($ARGV[0] !~ /^$/) {
            if($text =~ /($ARGV[0])/) {
               exit;
            }
         }

         $entryLines = 0;
      }
      else {
         $entry      = "$entry$text\n";
         $entryLines = $entryLines + 1;
      }
   }
}
