[project]
name = "p4c"
requires-python = ">=3.8"

[flake8]
max-line-length = 100
max-complexity = 10
extend-ignore = "E203"

[tool.isort]
profile = 'black'
line_length = 100

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.mypy]
namespace_packages = true
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true

[tool.pylint.main]
init-hook="from pylint.config import find_default_config_files; import os, sys; sys.path.append(os.path.dirname(next(find_default_config_files())))"
[tool.pylint.messages_control]
max-line-length = 100
disable = [
  "missing-docstring",
  "missing-function-docstring",
  "too-few-public-methods",
]
