#ifndef BACKENDS_TOFINO_BF_ASM_TEST_PTF_P4FEATURES_H_
#define BACKENDS_TOFINO_BF_ASM_TEST_PTF_P4FEATURES_H_

#define MATCH_ATCAM
#define MATCH_COUNT 50000
#define STATS_INDIRECT
#define STATS_COUNT 18000
#define STATEFUL_INDIRECT
#define STATEFUL_COUNT 40000
#define ACTION_DIRECT
#define ACTION_COUNT 50000

#endif /* BACKENDS_TOFINO_BF_ASM_TEST_PTF_P4FEATURES_H_ */
