#!/bin/bash -x
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
P4C_DIR=${SCRIPT_DIR}/../../../

pushd $SCRIPT_DIR/libbpf/src
mkdir build root
BUILD_STATIC_ONLY=y OBJDIR=build DESTDIR=root make install
popd
mkdir -p ${SCRIPT_DIR}/include/bpf/
cp ${SCRIPT_DIR}/libbpf/src/*.h ${SCRIPT_DIR}/include/bpf/
cp ${P4C_DIR}/backends/ebpf/runtime/*.h ${SCRIPT_DIR}/include/bpf/
