#!/bin/bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: THIS SCRIPT SHOULD NOT BE EXECUTED MANUALLY

RUNTIME_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
EXTRACT_DIR="$RUNTIME_DIR/extracted_deb"

if ! [ -f "$RUNTIME_DIR/setup" ]; then
    echo "setup and cleanup script should be in the same directory"
    exit 1
fi

rm -rf $EXTRACT_DIR
rm -f $RUNTIME_DIR/id_rsa
rm -f $RUNTIME_DIR/id_rsa.pub
rm -f linux-image-*.deb

deluser ci --remove-home
