#!/usr/bin/env python3
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
from scapy.all import sendp, rdpcap

PARSER = argparse.ArgumentParser()
PARSER.add_argument("pcap_file", help="PCAP file to send")
PARSER.add_argument("iface", help="Interface to send the pcap to")


def main():
    args, _ = PARSER.parse_known_args()

    pcap_file = args.pcap_file
    iface = args.iface

    packets = rdpcap(pcap_file)
    print("pcap_file", pcap_file)
    print("iface", iface)
    print("packets", packets)
    for packet in packets:
        print("packet", packet)
        sendp(packet, iface=iface)


if __name__ == "__main__":
    main()
