#!/bin/bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

RUNTIME_DIR=$1
EXTRACT_URL=$2

$RUNTIME_DIR/clone-iproute2 $RUNTIME_DIR
$RUNTIME_DIR/build-iproute2 $RUNTIME_DIR

$RUNTIME_DIR/extract_deb $EXTRACT_URL

sudo useradd -s /bin/bash -m ci

yes y | ssh-keygen -q -f $RUNTIME_DIR/id_rsa -N ''
