#################################################################
# 
#################################################################

ifndef BIGCODE
include ../../../../init.mk
endif

ucli:
	$(BIGCODE)/Tools/uclihandlers.py testmod_ucli.c



