/****************************************************************
 * 
 ***************************************************************/
#include <stddef.h>

#include <testmod/testmod_config.h>

#if TESTMOD_CONFIG_INCLUDE_UCLI == 1

#include <uCli/ucli.h>
#include <uCli/ucli_argparse.h>
#include <uCli/ucli_handler_macros.h>

static ucli_status_t
testmod_ucli_ucli__config__(ucli_context_t* uc)
{
    UCLI_HANDLER_MACRO_MODULE_CONFIG(testmod);
}

/* <auto.ucli.handlers.start> */
/******************************************************************************
 *
 * These handler table(s) were autogenerated from the symbols in this 
 * source file. 
 *
 *****************************************************************************/
static ucli_command_handler_f testmod_ucli_ucli_handlers__[] = 
{
    testmod_ucli_ucli__config__,
    NULL
};
/******************************************************************************/
/* <auto.ucli.handlers.end> */


static ucli_module_t
testmod_ucli_module__ = 
    {
        "testmod_ucli", 
        NULL, 
        testmod_ucli_ucli_handlers__, 
        NULL, 
        NULL, 
    }; 


ucli_node_t*
testmod_ucli_node_create(void)
{
    ucli_node_t* n; 
    ucli_module_init(&testmod_ucli_module__); 
    n = ucli_node_create("testmod", NULL, &testmod_ucli_module__); 
    ucli_node_subnode_add(n, ucli_module_log_node_create("testmod")); 
    return n;
}

#else
void*
testmod_ucli_node_create(void)
{
    return NULL; 
}
#endif



