
###############################################################################
#
# Inclusive Makefile for the behavioral_sim module.
#
# Autogenerated 2015-01-26 13:52:30.160066
#
###############################################################################
behavioral_sim_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(behavioral_sim_BASEDIR)/module/make.mk
include $(behavioral_sim_BASEDIR)/module/src/make.mk
include $(behavioral_sim_BASEDIR)/module/auto/make.mk
include $(behavioral_sim_BASEDIR)/utest/_make.mk

