###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := behavioral_sim
AUTOMODULE := behavioral_sim
include $(BUILDER)/definemodule.mk
