
###############################################################################
#
# Inclusive Makefile for the simple_switch module.
#
# Autogenerated 2015-02-26 16:16:01.869252
#
###############################################################################
simple_switch_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

