#!/bin/bash

# Script for building in a Docker container on Travis.

set -e  # Exit on error.

export P4C_DEPS="bison \
             build-essential \
             cmake \
             curl \
             flex \
             g++ \
             libboost-dev \
             libboost-graph-dev \
             libboost-iostreams1.58-dev \
             libfl-dev \
             libgc-dev \
             libgmp-dev \
             pkg-config \
             python \
             python3 \
             python3-pip \
             python3-setuptools \
             tcpdump"

export P4C_EBPF_DEPS="libpcap-dev \
             libelf-dev \
             zlib1g-dev \
             llvm \
             clang \
             net-tools"

export P4C_RUNTIME_DEPS="cpp \
                     libboost-graph1.58.0 \
                     libboost-iostreams1.58.0 \
                     libgc1c2 \
                     libgmp10 \
                     libgmpxx4ldbl \
                     python3"

export P4C_PIP_PACKAGES="ipaddr \
                     pyroute2 \
                     ply==3.8 \
                     scapy==2.4.0"

export P4C_PIP3_PACKAGES="ipaddr \
                          pyroute2 \
                          ply==3.8 \
                          scapy"

apt-get update
apt-get install -y --no-install-recommends \
  ${P4C_DEPS} \
  ${P4C_EBPF_DEPS} \
  ${P4C_RUNTIME_DEPS} \
  git

pip3 install wheel
pip3 install $P4C_PIP3_PACKAGES

# Build libbpf for eBPF tests.
cd /p4c
python3 backends/ebpf/build_libbpf
cd -

# We also need to build iproute2 from source to support Ubuntu 16.04 eBPF.
cd /tmp
git clone -b v5.0.0 git://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git
cd /tmp/iproute2
./configure
make -j `getconf _NPROCESSORS_ONLN` && \
make install
cd /p4c
rm -rf /tmp/pip
# iproute2-end


# ! ------- BEGIN Python2 -------------------------------------------------
# ! ------- Should be deleted when conversion to Python3 is finalized -----
# We install pip with get-pip.py (https://pip.pypa.io/en/stable/installing/)
# since the Ubuntu package manager's version of pip seems to be broken on
# Ubuntu 16.04.
mkdir /tmp/pip
cd /tmp/pip
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python2 get-pip.py
cd -
rm -rf /tmp/pip

# just to make sure we don't break other downstream projects that have
# not yet converted, we still install python2 and the modules
pip install $P4C_PIP_PACKAGES
# ! ------  END Python2 ----------------------------------------------------

function build() {
  if [ -e build ]; then /bin/rm -rf build; fi
  mkdir -p build
  cd build

  cmake .. '-DCMAKE_CXX_FLAGS:STRING=-O3' "$@"
  make
}

build "-DENABLE_UNIFIED_COMPILATION=${ENABLE_UNIFIED_COMPILATION}"

make install
/usr/local/bin/ccache -p -s

if [[ "${IMAGE_TYPE}" == "build" ]] ; then
  apt-get purge -y ${P4C_DEPS} git
  apt-get autoremove --purge -y
  rm -rf /p4c /var/cache/apt/* /var/lib/apt/lists/*
  echo 'Build image ready'

elif [[ "${IMAGE_TYPE}" == "test" ]] ; then
  echo 'Test image ready'

fi
