/* Automatically generated by p4c-ubpf from /home/dev/workspace/p4c/testdata/p4_16_samples/action_call_ubpf.p4
 */
#include "action_call_ubpf.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "ubpf_common.h"

#define BPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)

void* memcpy(void* dest, const void* src, size_t num);

static void *(*ubpf_map_lookup)(const void *, const void *) = (void *)1;
static int (*ubpf_map_update)(void *, const void *, void *) = (void *)2;
static int (*ubpf_map_delete)(void *, const void *) = (void *)3;
static int (*ubpf_map_add)(void *, const void *) = (void *)4;
static uint64_t (*ubpf_time_get_ns)() = (void *)5;
static uint32_t (*ubpf_hash)(const void *, uint64_t) = (void *)6;
static void (*ubpf_printf)(const char *fmt, ...) = (void *)7;
static void *(*ubpf_packet_data)(const void *) = (void *)9;
static void *(*ubpf_adjust_head)(const void *, uint64_t) = (void *)8;


#define write_partial(a, w, s, v) do { *((uint8_t*)a) = ((*((uint8_t*)a)) & ~(BPF_MASK(uint8_t, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(uint8_t*)((base) + (offset)) = (v); } while (0)

static uint32_t
bpf_htonl(uint32_t val) {
    return htonl(val);
}
static uint16_t
bpf_htons(uint16_t val) {
    return htons(val);
}
static uint64_t
bpf_htonll(uint64_t val) {
    return htonll(val);
}

uint64_t entry(void *ctx, uint64_t pkt_len){
    void *pkt = ubpf_packet_data(ctx);
    struct Headers_t headers = {
    };
    struct metadata meta = {
    };
    int packetOffsetInBits = 0;
    uint8_t pass = 1;
    unsigned char ebpf_byte;
    int head_len = 0;

    if (sizeof(struct Headers_t) < pkt_len) {
        return 0;
    }

    goto start;
    start: {
        goto accept;
    }

    reject: { return 0; }

    accept:
    {
        {

            {
                /* value */
                struct pipe_test_tbl_value *value = NULL;

                if (value != NULL) {
                    /* run action */
                    switch (value->action) {
                        case pipe_RejectConditional:
                        {

                        }
                        break;
                        case pipe_act_return:
                        {
                            pass = true;

                        }
                        break;
                        case pipe_act_exit:
                        {
                            pass = true;

                        }
                        break;
                        default: return 0;
                    }
                }
                else return 0;
            }
;

            goto deparser;
        }    }
    deparser:
    packetOffsetInBits = 0;
    pkt = ubpf_adjust_head(ctx, head_len);
    if (pass)
        return 1;
    else
        return 0;
}
