/* Automatically generated by p4c-ubpf from /home/dev/workspace/p4c/testdata/p4_16_samples/hash_ubpf.p4
 */
#include "hash_ubpf.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "ubpf_common.h"

#define BPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)

void* memcpy(void* dest, const void* src, size_t num);

static void *(*ubpf_map_lookup)(const void *, const void *) = (void *)1;
static int (*ubpf_map_update)(void *, const void *, void *) = (void *)2;
static int (*ubpf_map_delete)(void *, const void *) = (void *)3;
static int (*ubpf_map_add)(void *, const void *) = (void *)4;
static uint64_t (*ubpf_time_get_ns)() = (void *)5;
static uint32_t (*ubpf_hash)(const void *, uint64_t) = (void *)6;
static void (*ubpf_printf)(const char *fmt, ...) = (void *)7;
static void *(*ubpf_packet_data)(const void *) = (void *)9;
static void *(*ubpf_adjust_head)(const void *, uint64_t) = (void *)8;


#define write_partial(a, w, s, v) do { *((uint8_t*)a) = ((*((uint8_t*)a)) & ~(BPF_MASK(uint8_t, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(uint8_t*)((base) + (offset)) = (v); } while (0)

static uint32_t
bpf_htonl(uint32_t val) {
    return htonl(val);
}
static uint16_t
bpf_htons(uint16_t val) {
    return htons(val);
}
static uint64_t
bpf_htonll(uint64_t val) {
    return htonll(val);
}

uint64_t entry(void *ctx, uint64_t pkt_len){
    void *pkt = ubpf_packet_data(ctx);
    struct Headers_t headers = {
        .test = {
            .ebpf_valid = 0
        },
        .test1 = {
            .ebpf_valid = 0
        },
        .test2 = {
            .ebpf_valid = 0
        },
    };
    struct metadata meta = {
        .output = 0,
    };
    int packetOffsetInBits = 0;
    uint8_t pass = 1;
    unsigned char ebpf_byte;
    int head_len = 0;

    if (sizeof(struct Headers_t) < pkt_len) {
        return 0;
    }

    goto start;
    start: {
        goto accept;
    }

    reject: { return 0; }

    accept:
    {
        {

            {

                struct tuple_0 {
                    uint16_t field_0;
                    uint8_t field_1;
                    uint8_t pad0[1];
                };
                struct tuple_0 hash_key_instance = {
                    .pad0 = {0},
                };
                hash_key_instance.field_0 = headers.test.sa;
                hash_key_instance.field_1 = headers.test.da;
                meta.output = ubpf_hash(&hash_key_instance, sizeof(hash_key_instance));

            };

            {

                struct tuple_1 {
                    uint8_t field_0;
                    uint8_t pad0[1];
                    uint16_t field_1;
                    uint16_t field_2;
                    uint8_t field_3;
                    uint8_t pad1[1];
                };
                struct tuple_1 hash_key_instance_0 = {
                    .pad0 = {0},
                    .pad1 = {0},
                };
                hash_key_instance_0.field_0 = headers.test1.a;
                hash_key_instance_0.field_1 = headers.test1.b;
                hash_key_instance_0.field_2 = headers.test1.c;
                hash_key_instance_0.field_3 = headers.test1.d;
                meta.output = ubpf_hash(&hash_key_instance_0, sizeof(hash_key_instance_0));

            };

            {

                struct tuple_2 {
                    uint8_t field_0;
                    uint8_t pad0[1];
                };
                struct tuple_2 hash_key_instance_1 = {
                    .pad0 = {0},
                };
                hash_key_instance_1.field_0 = headers.test2.a;
                meta.output = ubpf_hash(&hash_key_instance_1, sizeof(hash_key_instance_1));

            };

        }    }
    deparser:
    packetOffsetInBits = 0;
    pkt = ubpf_adjust_head(ctx, head_len);
    if (pass)
        return 1;
    else
        return 0;
}
