name: "p4c-dpdk-ptf-p4testgen-tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

# Cancel any preceding run on the pull request.
concurrency:
  group: p4c-dpdk-ptf-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Envs for infrap4d and dpdk libs.
# IPDK_INSTALL_DIR is set to a default search directory for
# visibility of different libs like libprotobuf.
env:
  IPDK_INSTALL_DIR: ${{ github.workspace }}/ipdk_install
  CMAKE_UNITY_BUILD: ON
  ENABLE_TEST_TOOLS: ON
  ENABLE_DPDK: ON
  ENABLE_BMV2: OFF
  ENABLE_EBPF: OFF
  IMAGE_TYPE: test
  CTEST_PARALLEL_LEVEL: 4
  BUILD_GENERATOR: Ninja

jobs:
  build-p4dpdk-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ptf-${{ runner.os }}-test
          max-size: 1000M

      - name: Checkout DPDK target
        uses: actions/checkout@v6
        with:
          repository: p4lang/p4-dpdk-target
          path: p4sde
          submodules: recursive

      - name: Checkout ipdk-recipe
        uses: actions/checkout@v6
        with:
          repository: ipdk-io/networking-recipe
          path: ipdk.recipe
          submodules: recursive

      - name: Checkout P4C
        uses: actions/checkout@v6
        with:
          path: p4c
          submodules: recursive
          fetch-depth: 0

      - name: Install hugepages and set transparent hugepages to madvise
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libhugetlbfs-bin
          sudo hugeadm --thp-madvise

      - name: Install DPDK dependencies
        working-directory: p4sde/tools/setup
        run: |
          sudo apt-get update -y
          python3 install_dep.py

      - name: Compile p4sde dpdk target
        working-directory: p4sde
        run: |
          ./autogen.sh
          ./configure --prefix="$IPDK_INSTALL_DIR"
          make
          make install

      - name: Build infrap4d dependencies
        working-directory: ipdk.recipe
        run: |
          sudo apt-get install -y libatomic1 libnl-route-3-dev openssl
          pip3 install -r requirements.txt
          cd setup
          cmake -B build -DCMAKE_INSTALL_PREFIX="$IPDK_INSTALL_DIR"
          cmake --build build

      - name: Build infrap4d
        working-directory: ipdk.recipe
        run: |
          ./make-all.sh --target=dpdk --no-krnlmon --no-ovs -S "$IPDK_INSTALL_DIR" -D "$IPDK_INSTALL_DIR" --prefix="$IPDK_INSTALL_DIR"

      - name: Build P4C with only the DPDK backend
        working-directory: p4c
        run: |
          export CMAKE_FLAGS+="-DENABLE_BMV2=OFF "
          export CMAKE_FLAGS+="-DENABLE_EBPF=OFF "
          export CMAKE_FLAGS+="-DENABLE_UBPF=OFF "
          export CMAKE_FLAGS+="-DENABLE_GTESTS=OFF "
          export CMAKE_FLAGS+="-DENABLE_P4TEST=OFF "
          export CMAKE_FLAGS+="-DENABLE_P4TC=OFF "
          export CMAKE_FLAGS+="-DENABLE_P4C_GRAPHS=OFF "
          export CMAKE_FLAGS+="-DENABLE_TEST_TOOLS=ON "
          export CMAKE_FLAGS+="-DIPDK_INSTALL_DIR=$IPDK_INSTALL_DIR "
          tools/ci-build.sh

      - name: Run DPDK PTF tests using P4Testgen
        working-directory: p4c/build
        run: |
          sudo "$IPDK_INSTALL_DIR"/sbin/set_hugepages.sh
          sudo -E env PATH="$PATH" ctest -j1 --output-on-failure --schedule-random -R "testgen-p4c-pna-ptf|dpdk-ptf"
